#!/usr/bin/python
# pip install vk
import vk
from time import sleep

fro = %id%
to = fro-8

token = ''
vkapi = vk.API(vk.Session(access_token=token))
while fro != 0:
    for i in range(fro,to,-1):
        try:
            vkapi.messages.restore(message_id=i)
            print(i)
        except Exception as e:
            print e
    fro -= 8
    to -= 8
    sleep(2)
